spring:
  main:
    banner-mode: off
  application:
    name: PokemonAO

  jpa:
    hibernate:
      ddl-auto: create


    properties:
      hibernate:
        format_sql: true
        default_schema: pokemon_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret